// <auto-generated />
using System;
using LJA.FinancialTransaction.Persistence.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LJA.FinancialTransaction.Persistence.Migrations
{
    [DbContext(typeof(FinancialTransactionDbContext))]
    [Migration("20250717194118_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LJA.FinancialTransaction.Models.Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Revenue"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Expenses"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Assets"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Liabilities"
                        });
                });

            modelBuilder.Entity("LJA.FinancialTransaction.Models.Sources", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bank Transfer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Credit Card"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cash"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Check"
                        });
                });

            modelBuilder.Entity("LJA.FinancialTransaction.Models.Transactions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SourceId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1.00m,
                            CategoryId = 1,
                            Date = new DateTime(2025, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Description 1",
                            SourceId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 2.00m,
                            CategoryId = 1,
                            Date = new DateTime(2025, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Description 2",
                            SourceId = 2
                        },
                        new
                        {
                            Id = 3,
                            Amount = 3.00m,
                            CategoryId = 2,
                            Date = new DateTime(2025, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Description 3",
                            SourceId = 1
                        },
                        new
                        {
                            Id = 4,
                            Amount = 4.00m,
                            CategoryId = 2,
                            Date = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Description 4",
                            SourceId = 2
                        },
                        new
                        {
                            Id = 5,
                            Amount = 5.00m,
                            CategoryId = 3,
                            Date = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Description 5",
                            SourceId = 1
                        },
                        new
                        {
                            Id = 6,
                            Amount = 6.00m,
                            CategoryId = 3,
                            Date = new DateTime(2025, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Description 6",
                            SourceId = 2
                        },
                        new
                        {
                            Id = 7,
                            Amount = 7.00m,
                            CategoryId = 3,
                            Date = new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Description 7",
                            SourceId = 3
                        },
                        new
                        {
                            Id = 8,
                            Amount = 8.00m,
                            CategoryId = 4,
                            Date = new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Description 8",
                            SourceId = 1
                        },
                        new
                        {
                            Id = 9,
                            Amount = 9.00m,
                            CategoryId = 4,
                            Date = new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Description 9",
                            SourceId = 3
                        },
                        new
                        {
                            Id = 10,
                            Amount = 10.00m,
                            CategoryId = 4,
                            Date = new DateTime(2025, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Description 10",
                            SourceId = 4
                        });
                });

            modelBuilder.Entity("LJA.FinancialTransaction.Models.Transactions", b =>
                {
                    b.HasOne("LJA.FinancialTransaction.Models.Categories", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LJA.FinancialTransaction.Models.Sources", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
